name: snowflake_ds
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.3.1
  - pyarrow=18.1.0
  - jupyterlab=4.4.4
  - tabulate=0.9.0
  - snowflake-telemetry-python=0.5.0
  - snowflake=1.7.0
  - scikit-learn=1.5.1
  - fastparquet=2024.2.0
  - matplotlib=3.10.6
  - snowflake-snowpark-python=1.38.0
  - snowflake-ml-python=1.19.0